"""Minimal graph-first rlmflow.

The recursive execution graph is the source of truth: every query, action,
observation, child call, wait, resume, and result is a typed node you can
inspect, step, save, fork, and edit mid-run.
"""

from rlmflow.consumers import (
    ConsumerGroup,
    GraphCheckpointer,
    LiveGraphTree,
    LiveTreeRenderer,
    StreamConsumer,
    WorkspaceSync,
    render_tree,
)
from rlmflow.consumers.tui import FlowTUI
from rlmflow.flow import Flow, code_block
from rlmflow.graph import (
    ActionNode,
    AddChild,
    AppendNode,
    DoneOutput,
    ErrorOutput,
    Event,
    ExecAction,
    ExecOutput,
    Graph,
    GraphAction,
    GraphCheckpoint,
    GraphCreated,
    InsertNode,
    LLMOutput,
    LLMUsage,
    Node,
    ObservationNode,
    RemoveChild,
    RemoveNode,
    ReplaceNode,
    ResumeAction,
    SupervisingOutput,
    UserQuery,
    apply_graph_action,
    load_run,
    node_from_dict,
)
from rlmflow.integrations import DSPyFlow, FlowLLM, messages_to_query
from rlmflow.parallel import parallel_run, parallel_stream
from rlmflow.pool import Pool, SequentialPool, ThreadPool
from rlmflow.prompts import (
    DEFAULT_BUILDER,
    SYSTEM_PROMPT,
    PromptBuilder,
    PromptProfile,
    SystemPromptBuilder,
    UserPromptBuilder,
)
from rlmflow.runtime import (
    DockerRuntime,
    DoneSignal,
    LocalRepl,
    LocalRuntime,
    MissingReplError,
    ModalRuntime,
    RemoteRepl,
    Repl,
    Runtime,
    SubprocessRuntime,
)
from rlmflow.structured import (
    Schema,
    StructuredOutputError,
    StructuredOutputParser,
    json_schema_for,
)
from rlmflow.tools import (
    FILE_TOOLS,
    ToolMetadata,
    enable_graph_ops,
    format_tool_line,
    get_tool_metadata,
    inject_tools,
    register_halt,
    tool,
)
from rlmflow.utils import find_code_blocks
from rlmflow.utils.viewer import (
    open_viewer,
    render_steps,
    replay,
    save_gif,
    save_image,
    save_steps,
)

__all__ = [
    "ActionNode",
    "AddChild",
    "AppendNode",
    "ConsumerGroup",
    "DEFAULT_BUILDER",
    "DoneOutput",
    "DoneSignal",
    "DockerRuntime",
    "ErrorOutput",
    "Event",
    "ExecAction",
    "ExecOutput",
    "FILE_TOOLS",
    "find_code_blocks",
    "Flow",
    "FlowLLM",
    "FlowTUI",
    "Graph",
    "GraphAction",
    "GraphCheckpoint",
    "GraphCheckpointer",
    "GraphCreated",
    "InsertNode",
    "LLMOutput",
    "LLMUsage",
    "LiveGraphTree",
    "LiveTreeRenderer",
    "LocalRepl",
    "LocalRuntime",
    "MissingReplError",
    "ModalRuntime",
    "DSPyFlow",
    "Node",
    "ObservationNode",
    "open_viewer",
    "Pool",
    "PromptBuilder",
    "PromptProfile",
    "SystemPromptBuilder",
    "UserPromptBuilder",
    "replay",
    "render_steps",
    "save_gif",
    "save_image",
    "save_steps",
    "RemoteRepl",
    "Repl",
    "RemoveChild",
    "RemoveNode",
    "ReplaceNode",
    "ResumeAction",
    "Runtime",
    "SYSTEM_PROMPT",
    "Schema",
    "SequentialPool",
    "StructuredOutputError",
    "StructuredOutputParser",
    "SubprocessRuntime",
    "SupervisingOutput",
    "StreamConsumer",
    "ThreadPool",
    "ToolMetadata",
    "UserQuery",
    "WorkspaceSync",
    "apply_graph_action",
    "code_block",
    "enable_graph_ops",
    "format_tool_line",
    "get_tool_metadata",
    "inject_tools",
    "json_schema_for",
    "load_run",
    "messages_to_query",
    "node_from_dict",
    "parallel_run",
    "parallel_stream",
    "register_halt",
    "render_tree",
    "tool",
]
