"""Build recursive agents as inspectable node trees."""

from importlib import import_module
from typing import Any

from rlmflow.consumers import (
    ConsumerGroup,
    FlowTUI,
    GraphCheckpointer,
    LiveGraphTree,
    LiveTreeRenderer,
    StreamConsumer,
    WorkspaceSync,
    render_forest,
    render_tree,
)
from rlmflow.engine import boundaries
from rlmflow.engine.execution import Pool, SequentialPool, TaskQueue, ThreadPool, Transition
from rlmflow.engine.parallel import parallel_run, parallel_stream
from rlmflow.engine.steps import (
    ExecActionStep,
    LLMOutputStep,
    LLMRequestStep,
    MessageBuilder,
    StepFunction,
    append_run_result,
)
from rlmflow.graph import persistence
from rlmflow.graph.nodes import (
    DEFAULT_MAX_QUERY_CHARS,
    DEFAULT_QUERY,
    AgentConfig,
    AgentStart,
    AppendChild,
    ContinueQuery,
    DoneOutput,
    ErrorOutput,
    ExecAction,
    ExecOutput,
    FinalQuery,
    InspectQuery,
    LLMOutput,
    Node,
    PlanQuery,
    ReplDead,
    TruncationSummary,
    UserQuery,
    start,
)
from rlmflow.llm import (
    AnthropicClient,
    LLMChunk,
    LLMClient,
    LLMUsage,
    OpenAIClient,
    PooledLLMClient,
    TinkerClient,
    is_retryable,
    retry_transient,
)
from rlmflow.prompts import (
    DEFAULT_BUILDER,
    SYSTEM_PROMPT,
    PromptBuilder,
    PromptProfile,
    RenderFn,
    SystemPromptBuilder,
    default_render,
)
from rlmflow.runtime import (
    DockerRuntime,
    DoneSignal,
    LocalRuntime,
    MissingReplError,
    ModalRuntime,
    Repl,
    ReplRun,
    ReplStatus,
    Runtime,
    SubprocessRuntime,
    WorkerRepl,
    WorkerSession,
    WrappedRuntime,
)
from rlmflow.structured import (
    Schema,
    StructuredOutputError,
    StructuredOutputParser,
    json_schema_for,
    parse_structured_output,
    system_prompt_hint,
)
from rlmflow.tools import (
    FILE_TOOLS,
    AgentDirectory,
    AgentFrontier,
    AgentHandle,
    AgentInfo,
    AgentStatus,
    ToolMetadata,
    format_tool_line,
    get_tool_metadata,
    tool,
)
from rlmflow.utils import find_code_blocks

#: Names resolved on first access. ``flow`` because it pulls in the shared prompt
#: stack, which imports these nodes back, so an eager import is a cycle;
#: ``adapters`` because it probes for ``dspy``, which is slow and optional;
#: ``view`` because two of its renderers carry optional dependencies, and a run
#: that never draws itself should not pay for them.
_LAZY = {
    "Flow": "rlmflow.flow",
    "StepUntil": "rlmflow.flow",
    "code_block": "rlmflow.utils.helpers",
    "DSPyFlow": "rlmflow.adapters",
    "FlowLLM": "rlmflow.adapters",
    "messages_to_query": "rlmflow.adapters",
    "graph_svg": "rlmflow.view",
    "open_viewer": "rlmflow.view",
    "render_html": "rlmflow.view",
    "render_steps": "rlmflow.view",
    "replay": "rlmflow.view",
    "save_frames": "rlmflow.view",
    "save_gif": "rlmflow.view",
    "save_html": "rlmflow.view",
    "save_svg": "rlmflow.view",
    "snapshot": "rlmflow.view",
    "steps": "rlmflow.view",
    "timeline": "rlmflow.view",
}


def __getattr__(name: str) -> Any:
    if name == "view":
        return import_module("rlmflow.view")
    module = _LAZY.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(import_module(module), name)


__all__ = [
    "DEFAULT_BUILDER",
    "DEFAULT_MAX_QUERY_CHARS",
    "DEFAULT_QUERY",
    "FILE_TOOLS",
    "SYSTEM_PROMPT",
    "AgentConfig",
    "AgentDirectory",
    "AgentFrontier",
    "AgentHandle",
    "AgentInfo",
    "AgentStart",
    "AgentStatus",
    "AnthropicClient",
    "AppendChild",
    "ConsumerGroup",
    "ContinueQuery",
    "DSPyFlow",
    "DockerRuntime",
    "DoneOutput",
    "DoneSignal",
    "ErrorOutput",
    "ExecAction",
    "ExecActionStep",
    "ExecOutput",
    "FinalQuery",
    "Flow",
    "FlowLLM",
    "FlowTUI",
    "GraphCheckpointer",
    "InspectQuery",
    "LLMChunk",
    "LLMClient",
    "LLMOutput",
    "LLMOutputStep",
    "LLMUsage",
    "LiveGraphTree",
    "LiveTreeRenderer",
    "LocalRuntime",
    "MessageBuilder",
    "MissingReplError",
    "ModalRuntime",
    "Node",
    "OpenAIClient",
    "PooledLLMClient",
    "PlanQuery",
    "Pool",
    "PromptBuilder",
    "PromptProfile",
    "RenderFn",
    "Repl",
    "ReplDead",
    "ReplRun",
    "ReplStatus",
    "Runtime",
    "Schema",
    "SequentialPool",
    "StepUntil",
    "StepFunction",
    "StreamConsumer",
    "StructuredOutputError",
    "StructuredOutputParser",
    "SubprocessRuntime",
    "SystemPromptBuilder",
    "TaskQueue",
    "ThreadPool",
    "TinkerClient",
    "ToolMetadata",
    "Transition",
    "LLMRequestStep",
    "TruncationSummary",
    "WorkerRepl",
    "WorkerSession",
    "UserQuery",
    "WrappedRuntime",
    "WorkspaceSync",
    "boundaries",
    "append_run_result",
    "code_block",
    "default_render",
    "find_code_blocks",
    "format_tool_line",
    "get_tool_metadata",
    "graph_svg",
    "is_retryable",
    "json_schema_for",
    "messages_to_query",
    "open_viewer",
    "parallel_run",
    "parallel_stream",
    "parse_structured_output",
    "persistence",
    "render_forest",
    "render_html",
    "render_steps",
    "render_tree",
    "replay",
    "retry_transient",
    "save_frames",
    "save_gif",
    "save_html",
    "save_svg",
    "snapshot",
    "start",
    "steps",
    "system_prompt_hint",
    "timeline",
    "tool",
    "view",
]
